# Workflow to Run UI Tests against production
---
name: Run UI Tests against production
on:
  schedule:
    - cron: "0 7 * * *"  # Run at 7 AM UTC (nightly builds should be done!)

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PRODUCTION_URL: https://sandmark.tarides.com
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r tests/requirements.txt
          sbase get chromedriver latest
      - name: Run tests with pytest
        run: pytest --data "${PRODUCTION_URL}" -k test_ui
