# Workflow to Run Python tests
---
name: Run Python Tests
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      USE_TEST_ARTIFACTS: 1
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r tests/requirements.txt
          sbase get chromedriver
      - name: Start Streamlit app
        run: |
          streamlit run app/app.py --server.headless true &
      - name: Run tests with pytest
        run: pytest
